# Generated by Django 3.1.6 on 2021-08-12 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PROJECT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('desc', models.CharField(max_length=900)),
                ('state', models.IntegerField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(default=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Q_TABLE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=300)),
                ('field_type', models.IntegerField()),
                ('serial_number', models.IntegerField()),
                ('cell_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SUBMIT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField()),
                ('os', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionnaire.project')),
            ],
        ),
        migrations.CreateModel(
            name='QUESTION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('required', models.BooleanField()),
                ('type', models.IntegerField()),
                ('desc', models.CharField(max_length=900)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionnaire.project')),
            ],
        ),
        migrations.CreateModel(
            name='Q_TABLE_OPTIONS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionnaire.q_table')),
            ],
        ),
        migrations.AddField(
            model_name='q_table',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionnaire.question'),
        ),
        migrations.CreateModel(
            name='Q_NOTE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionnaire.question')),
            ],
        ),
        migrations.CreateModel(
            name='Q_IMAGE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('size', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionnaire.question')),
            ],
        ),
        migrations.CreateModel(
            name='Q_COMPLETION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('regex', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionnaire.question')),
            ],
        ),
        migrations.CreateModel(
            name='Q_CHOICE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionnaire.question')),
            ],
        ),
        migrations.CreateModel(
            name='ANSWER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionnaire.question')),
                ('submit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionnaire.submit')),
            ],
        ),
        migrations.CreateModel(
            name='A_TABLE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField()),
                ('content', models.TextField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionnaire.answer')),
                ('column_field', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='column', to='questionnaire.q_table')),
                ('row_field', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='row', to='questionnaire.q_table')),
            ],
        ),
        migrations.CreateModel(
            name='A_IMAGE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='images')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionnaire.answer')),
            ],
        ),
        migrations.CreateModel(
            name='A_COMPLETION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionnaire.answer')),
            ],
        ),
        migrations.CreateModel(
            name='A_CHOICE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionnaire.answer')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionnaire.q_choice')),
            ],
        ),
    ]
