# Generated by Django 3.1.6 on 2021-08-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.CharField(default='感谢参与调查！', max_length=900),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='q_completion',
            name='row',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
