# Generated by Django 3.1.6 on 2021-08-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20210816_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='random',
            field=models.BooleanField(default=False),
        ),
    ]
