# Generated by Django 3.1.6 on 2021-08-30 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_question_random'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='q_completion',
            name='row',
        ),
    ]
