# Generated by Django 3.1.6 on 2021-09-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_remove_q_completion_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='serial_number',
            field=models.IntegerField(default=0),
        ),
    ]
